/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SendRouteImport } from './routes/send'
import { Route as ReceiveRouteImport } from './routes/receive'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CreateCampaignRouteImport } from './routes/create-campaign'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CommunityUpdatesRouteImport } from './routes/community/updates'
import { Route as CommunitySupportRouteImport } from './routes/community/support'
import { Route as CommunityGeneralRouteImport } from './routes/community/general'
import { Route as CommunityFeaturesRouteImport } from './routes/community/features'
import { Route as CommunityBugsRouteImport } from './routes/community/bugs'
import { Route as CommunityAnnouncementsRouteImport } from './routes/community/announcements'

const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SendRoute = SendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiveRoute = ReceiveRouteImport.update({
  id: '/receive',
  path: '/receive',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateCampaignRoute = CreateCampaignRouteImport.update({
  id: '/create-campaign',
  path: '/create-campaign',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityUpdatesRoute = CommunityUpdatesRouteImport.update({
  id: '/community/updates',
  path: '/community/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitySupportRoute = CommunitySupportRouteImport.update({
  id: '/community/support',
  path: '/community/support',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityGeneralRoute = CommunityGeneralRouteImport.update({
  id: '/community/general',
  path: '/community/general',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityFeaturesRoute = CommunityFeaturesRouteImport.update({
  id: '/community/features',
  path: '/community/features',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityBugsRoute = CommunityBugsRouteImport.update({
  id: '/community/bugs',
  path: '/community/bugs',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityAnnouncementsRoute = CommunityAnnouncementsRouteImport.update({
  id: '/community/announcements',
  path: '/community/announcements',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/campaigns': typeof CampaignsRoute
  '/create-campaign': typeof CreateCampaignRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/receive': typeof ReceiveRoute
  '/send': typeof SendRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/transactions': typeof TransactionsRoute
  '/community/announcements': typeof CommunityAnnouncementsRoute
  '/community/bugs': typeof CommunityBugsRoute
  '/community/features': typeof CommunityFeaturesRoute
  '/community/general': typeof CommunityGeneralRoute
  '/community/support': typeof CommunitySupportRoute
  '/community/updates': typeof CommunityUpdatesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/campaigns': typeof CampaignsRoute
  '/create-campaign': typeof CreateCampaignRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/receive': typeof ReceiveRoute
  '/send': typeof SendRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/transactions': typeof TransactionsRoute
  '/community/announcements': typeof CommunityAnnouncementsRoute
  '/community/bugs': typeof CommunityBugsRoute
  '/community/features': typeof CommunityFeaturesRoute
  '/community/general': typeof CommunityGeneralRoute
  '/community/support': typeof CommunitySupportRoute
  '/community/updates': typeof CommunityUpdatesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/campaigns': typeof CampaignsRoute
  '/create-campaign': typeof CreateCampaignRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/receive': typeof ReceiveRoute
  '/send': typeof SendRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/transactions': typeof TransactionsRoute
  '/community/announcements': typeof CommunityAnnouncementsRoute
  '/community/bugs': typeof CommunityBugsRoute
  '/community/features': typeof CommunityFeaturesRoute
  '/community/general': typeof CommunityGeneralRoute
  '/community/support': typeof CommunitySupportRoute
  '/community/updates': typeof CommunityUpdatesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/campaigns'
    | '/create-campaign'
    | '/dashboard'
    | '/login'
    | '/profile'
    | '/receive'
    | '/send'
    | '/settings'
    | '/signup'
    | '/transactions'
    | '/community/announcements'
    | '/community/bugs'
    | '/community/features'
    | '/community/general'
    | '/community/support'
    | '/community/updates'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/campaigns'
    | '/create-campaign'
    | '/dashboard'
    | '/login'
    | '/profile'
    | '/receive'
    | '/send'
    | '/settings'
    | '/signup'
    | '/transactions'
    | '/community/announcements'
    | '/community/bugs'
    | '/community/features'
    | '/community/general'
    | '/community/support'
    | '/community/updates'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/campaigns'
    | '/create-campaign'
    | '/dashboard'
    | '/login'
    | '/profile'
    | '/receive'
    | '/send'
    | '/settings'
    | '/signup'
    | '/transactions'
    | '/community/announcements'
    | '/community/bugs'
    | '/community/features'
    | '/community/general'
    | '/community/support'
    | '/community/updates'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CampaignsRoute: typeof CampaignsRoute
  CreateCampaignRoute: typeof CreateCampaignRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  ReceiveRoute: typeof ReceiveRoute
  SendRoute: typeof SendRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  TransactionsRoute: typeof TransactionsRoute
  CommunityAnnouncementsRoute: typeof CommunityAnnouncementsRoute
  CommunityBugsRoute: typeof CommunityBugsRoute
  CommunityFeaturesRoute: typeof CommunityFeaturesRoute
  CommunityGeneralRoute: typeof CommunityGeneralRoute
  CommunitySupportRoute: typeof CommunitySupportRoute
  CommunityUpdatesRoute: typeof CommunityUpdatesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/send': {
      id: '/send'
      path: '/send'
      fullPath: '/send'
      preLoaderRoute: typeof SendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receive': {
      id: '/receive'
      path: '/receive'
      fullPath: '/receive'
      preLoaderRoute: typeof ReceiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-campaign': {
      id: '/create-campaign'
      path: '/create-campaign'
      fullPath: '/create-campaign'
      preLoaderRoute: typeof CreateCampaignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/updates': {
      id: '/community/updates'
      path: '/community/updates'
      fullPath: '/community/updates'
      preLoaderRoute: typeof CommunityUpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/support': {
      id: '/community/support'
      path: '/community/support'
      fullPath: '/community/support'
      preLoaderRoute: typeof CommunitySupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/general': {
      id: '/community/general'
      path: '/community/general'
      fullPath: '/community/general'
      preLoaderRoute: typeof CommunityGeneralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/features': {
      id: '/community/features'
      path: '/community/features'
      fullPath: '/community/features'
      preLoaderRoute: typeof CommunityFeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/bugs': {
      id: '/community/bugs'
      path: '/community/bugs'
      fullPath: '/community/bugs'
      preLoaderRoute: typeof CommunityBugsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/announcements': {
      id: '/community/announcements'
      path: '/community/announcements'
      fullPath: '/community/announcements'
      preLoaderRoute: typeof CommunityAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  CampaignsRoute: CampaignsRoute,
  CreateCampaignRoute: CreateCampaignRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  ReceiveRoute: ReceiveRoute,
  SendRoute: SendRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  TransactionsRoute: TransactionsRoute,
  CommunityAnnouncementsRoute: CommunityAnnouncementsRoute,
  CommunityBugsRoute: CommunityBugsRoute,
  CommunityFeaturesRoute: CommunityFeaturesRoute,
  CommunityGeneralRoute: CommunityGeneralRoute,
  CommunitySupportRoute: CommunitySupportRoute,
  CommunityUpdatesRoute: CommunityUpdatesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
